### ISSUE TITLE
Javamail 1.6.2 "break attachments names" regression

### ISSUE THREAD

**Issue by patton73** [eclipse-ee4j/mail#358]
Java mail version 1.6.2 does not respect properties setting about attachment names

Properties props = System.getProperties();
props.put("mail.mime.encodefilename", "false");
props.put("mail.mime.encodeparameters", "false");

I have attached the code to reproduce the bug.
I have also attached 2 eml generated with correct and wrong names for the attachments.

What I expect is that if i set the above properties then javamail should generate and eml without broken up attachments names (you can see it in the attached file correct.output.zip)
If i do not set the parameters then the i expect javamail to break up attachment names (you can see it in the wrong.output.zip file).
The bug is related to the fact that basically javamail ignores the properties and always breaks up the attachement names.

Java mail 1.6.1 is not affected by this regression.
Thanks for any help.

[Main.txt](https://github.com/eclipse-ee4j/javamail/files/2607757/Main.txt)
[correct output.zip](https://github.com/eclipse-ee4j/javamail/files/2607760/correct.output.zip)
[wrong output.zip](https://github.com/eclipse-ee4j/javamail/files/2607761/wrong.output.zip)

**Comment by bshannon** [comment]
I don't see the problem.  The attachment names are exactly the same in the two eml files you provided.

**Comment by patton73** [comment]
It was my fault. I will reload the correct files in a couple of days since i do not have access to them right now.
