### ISSUE TITLE
transport charset information is not respected for text/html

### ISSUE THREAD

**Issue by mpfau** [eclipse-ee4j/mail#394]
**Describe the bug**
As clearly defined in https://tools.ietf.org/html/rfc6657, for payloads such as "text/html" no charset parameters should be defined as part of the content type definition. Instead, the transport charset information should be used (inline).

JavaMail currently ignores the inline definition and parses documents without an explicit charset parameter for the content type as ISO-8859-1. This leads to garbage output in all cases where the actual charset is not ISO-8859-1.

**To Reproduce**
Run the testcase (below).

**Expected behavior**
The testcase should run successfully.

**Desktop (please complete the following information):**
 - OS: Debian 9

**Additional context**
Here is a testcase:
```
import org.junit.Test;

import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.internet.MimeMessage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.nio.charset.Charset;

import static junit.framework.TestCase.assertEquals;

public class EncodingTest {
	@Test
	public void respectInlineCharsetDefinition() throws IOException, MessagingException {
		String mail = "MIME-Version: 1.0\n" +
				"Content-Type: text/html\n" +
				"Content-Transfer-Encoding: 8bit\n" +
				"\n" +
				"<html><head><meta charset=\"utf-8\"></head><body><p>Благодарим Ви</p></body>";

		byte[] mailBytes = mail.getBytes(Charset.forName("UTF-8"));

		Session mailSession = Session.getDefaultInstance(System.getProperties(), null);
		MimeMessage message = new MimeMessage(mailSession, new ByteArrayInputStream(mailBytes));
		assertEquals("<html><head><meta charset=\"utf-8\"></head><body><p>Благодарим Ви</p></body>", message.getContent());
	}
}
```

**Comment by bshannon** [comment]
Yow!  What a horrible RFC!

This means there's no way to return a Java String object representing the text content
without knowing how to interpret the content as html or xml or whatever, then reading
the content as a byte stream, parsing the content according to the subtype, extracting the
charset value, then re-reading the content and constructing a Java String using the extracted
charset value.

Teaching Mail how to parse all these different subtypes, or adding dependencies on other
libraries to parse all these subtypes, seems excessive.  Most other mailers will duplicate
the subtype-specific charset information in the charset parameter, allowing the data to be
properly converted to a Unicode string without knowing how to parse the data.

An application can always do the hard work itself by reading the data using the getInputStream
method.  In many cases there will be no need to store the data in a Java String object so
processing it as a byte stream will give the intended result.

This is very likely a case of "will not fix", perhaps with a caveat added to the getContent method.

Note also that RFC 6657 explicitly says that it does not change the defaults for any currently
registered media types, so it's not clear this even applies to text/html and text/xml.

**Comment by mpfau** [comment]
Unfortunately, there are quite some mails out there where no charset is defined as part of the content type. E.g. Amazon SES happily sends them out (maybe also using JavaMail?).

For now, our workaround is to extract the charset from the String (getContent()) and get the input stream and decode explicitly if needed.

**Comment by mpfau** [comment]
> In all these cases, are the messages actually encoded using utf-8?
Those that I observed used utf-8. But there might be others.

> Well of course that depends on being able to construct a string using some other charset that will be correct enough that you can extract the real charset information from it.

That is true. It worked with my test messages where getContent() seemed to convert to ISO-8859-1. As  html headers usually contain only ASCII code it is no problem to extract the charset, then.

> What do you do with the content after constructing the final String? If all you do is save it or copy it, it might be better to just operate on the InputStream.

Thanks for the hint! We just encrypt and save it. We might switch to InputStream if the described approach fails with other messages...

**Comment by bshannon** [comment]
I'm going to close this as "will not fix" for now.  If it becomes a serious problem later, I'll reconsider.
