### ISSUE TITLE
finalizecleanclose false can send commands causing unhandled exception

### ISSUE THREAD

**Issue by M66B** [eclipse-ee4j/mail#400]
**Describe the bug**

*mail...finalizecleanclose* set to false the default:

"*When the finalizer for IMAPStore is called, should the connection to the server be closed cleanly, as if the application called the close method? Or should the connection to the server be closed without sending any commands to the server? Defaults to false, the connection is not closed cleanly.*"
https://javaee.github.io/javamail/docs/api/com/sun/mail/imap/package-summary.html

Still tries to send commands to the server, sometimes resulting an unhandled TimeoutException (only ProtocolException is catched in IMAPStore.emptyConnectionPool)

```
java.util.concurrent.TimeoutException: com.sun.mail.imap.IMAPSSLStore.finalize() timed out after 10 seconds
        at com.android.org.conscrypt.NativeCrypto.SSL_read(NativeCrypto.java:-2)
        at com.android.org.conscrypt.NativeSsl.read(NativeSsl.java:399)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:546)
        at com.sun.mail.util.TraceInputStream.read(SourceFile:102)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:248)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:267)
        at com.sun.mail.iap.ResponseInputStream.readResponse(SourceFile:79)
        at com.sun.mail.iap.Response.<init>(SourceFile:109)
        at com.sun.mail.imap.protocol.IMAPResponse.<init>(SourceFile:36)
        at com.sun.mail.imap.protocol.IMAPProtocol.readResponse(SourceFile:388)
        at com.sun.mail.iap.Protocol.command(SourceFile:371)
        at com.sun.mail.imap.protocol.IMAPProtocol.logout(SourceFile:465)
        at com.sun.mail.imap.IMAPStore.emptyConnectionPool(SourceFile:1392)
        at com.sun.mail.imap.IMAPStore.close(SourceFile:1606)
        at com.sun.mail.imap.IMAPStore.finalize(SourceFile:1620)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
        at java.lang.Daemons$Daemon.run(Daemons.java:103)
        at java.lang.Thread.run(Thread.java:764)
```

**Expected behavior**
Calling emptyConnectionPool in IMAPStore.close with force=true when finalizecleanclose is disabled.

**Comment by bshannon** [comment]
What version of JavaMail are you using?

I don't suppose you have a reproducible test case?

Looking at the latest code, I don't see how this can happen.  If finalizecleanclose is set to false,
forceClose should be set to true before the close method is called, which should cause the
cleanup method to call emptyConnectionPool with force=true, which should cause it to call
IMAPProtocol.disconnect instead of IMAPProtocol.logout.

**Comment by M66B** [comment]
JavaMail version 1.6.4

finalize calls close:
https://github.com/eclipse-ee4j/mail/blob/master/mail/src/main/java/com/sun/mail/imap/IMAPStore.java#L1620

close calls emptyConnectionPool(**false**):
https://github.com/eclipse-ee4j/mail/blob/master/mail/src/main/java/com/sun/mail/imap/IMAPStore.java#L1606

Therefore emptyConnectionPool does logout instead of disconnect:
https://github.com/eclipse-ee4j/mail/blob/master/mail/src/main/java/com/sun/mail/imap/IMAPStore.java#L1389

So, IMHO close should call emptyConnectionPool(**forceClose**) instead

**Comment by M66B** [comment]
Maybe also:

closeAllFolders(**forceClose**)

**Comment by bshannon** [comment]
Before close calls emptyConnectionPool(false), it calls cleanup.
cleanup calls emptyConnectionPool with the force flag dependent
on the setting of the forceClose flag, which is set to true in finalize.

After this first call to emptyConnectionPool, there should be no more
connections left in the pool so the second call to emptyConnectionPool(false)
should have nothing to do.

How are you reproducing the failure you're seeing?

**Comment by M66B** [comment]
I see the crash occasionally in Bugsnag (error report) of [FairEmail](https://github.com/M66B/FairEmail/). I haven't been able to reproduce it, but it happens in the wild.

finalizecleanclose is set to false here:
https://github.com/M66B/FairEmail/blob/master/app/src/main/java/eu/faircode/email/MailService.java#L110

**Comment by M66B** [comment]
Part of the stack trace:

at com.sun.mail.imap.protocol.IMAPProtocol.**logout**(SourceFile:465)

So, for some reason the flags aren't set right.

**Comment by M66B** [comment]
Maybe this remark in close is relevant:
// do these again in case cleanup returned early
// because we were already closed due to a failure

**Comment by bshannon** [comment]
If the store is already closed due to a failure, cleanup should've been called,
which should've emptied the connection pool.  I don't see how something could be
added to the connection pool without there also being a live pointer to the IMAPStore,
which would prevent the finalize method from being called.  There must be some race
condition in here that I'm missing.

**Comment by M66B** [comment]
I can't find it either, but it is happening, cause the app to crash.

I always prefer an explanation, but doing this wouldn't hurt I guess:

```
closeAllFolders(forceClose)
emptyConnectionPool(forceClose)
```

**Comment by bshannon** [comment]
Yes, that's probably the best choice.

**Comment by bshannon** [comment]
Please test the 1.6.5-SNAPSHOT release if you can.  Thanks.

**Comment by M66B** [comment]
I certainly will, thanks!

**Comment by M66B** [comment]
Maybe a stupid question, but at which maven coordinates can the snapshots be found?

**Comment by bshannon** [comment]
It's version 1.6.5-SNAPSHOT.  As described [here](https://eclipse-ee4j.github.io/mail/#Development_Releases), it's in the Sonatype OSSRH repository.

You'll need to enable that using something like this in your settings.xml:

```
            <repositories>
                <repository>
                    <id>sonatype-nexus-staging</id>
                    <name>Sonatype Nexus Staging</name>
                    <url>https://oss.sonatype.org/content/repositories/staging</url>
                    <releases>
                        <enabled>true</enabled>
                    </releases>
                    <snapshots>
                        <enabled>false</enabled>
                    </snapshots>
                </repository>
            </repositories>
```

**Comment by M66B** [comment]
Almost ;-)

staging -> snaphots

In Android Studio:
```
maven { url "https://oss.sonatype.org/content/repositories/snapshots"}
def javamail_version = "1.6.5-SNAPSHOT"
implementation "com.sun.mail:android-mail:$javamail_version"
implementation "com.sun.mail:android-activation:$javamail_version"
```

**Comment by M66B** [comment]
@bshannon I have not seen this problem anymore since this change
