### ISSUE TITLE
Mail subject not decoded

### ISSUE THREAD

**Issue by rgambelli** [eclipse-ee4j/mail#405]
**Describe the bug**
I have a mail with following header subject

Subject: =?UTF-8?B?UmlmLiBQcmF0LjogNDhBVi04MDc5IEF0dHJhdmVyc2FtZW50byB0ZWxlZm9uaWNvIHN1cGVyaW9yZSwgaW4gY2F2ZWRpbyBlc2lzdGVudGUsIGNvbiBjYXZpIGEgRi5PLiBhbCBrbSA2NCs0MjAgZGVsbGEgbGluZWEgZmVycm92aWFyaWEgQVYvQUMgVG9yaW5vIC0gTWlsYW5vIG5lbCBDb211bmUgZGkgR3JlZ2dpbyAgW1JGSS1EUFItRFRQX1RPLklOR1xQRUNcUFwyMDE5XDAwMDUyNDRd=?=

I'm using javamail 1.5.6 to parse it and parsing that header an exception is thrown which results in a not parsed subject:

MimeUtility class decodeWord method row 928

com.sun.mail.util.DecodingException: BASE64Decoder: Error in encoded stream: needed at least 2 valid base64 characters, but only got 0 before padding character (=), the 10 most recent characters were: "wMDUyNDRd="

I don't believe it's a wrongly encoded word because with an online decoder I was able to decode it,  anyway if I open that mail with Outlook the subject is read well.

For example this works fine:

```
String rawvalue = "UmlmLiBQcmF0LjogNDhBVi04MDc5IEF0dHJhdmVyc2FtZW50byB0ZWxlZm9uaWNvIHN1cGVyaW9yZSwgaW4gY2F2ZWRpbyBlc2lzdGVudGUsIGNvbiBjYXZpIGEgRi5PLiBhbCBrbSA2NCs0MjAgZGVsbGEgbGluZWEgZmVycm92aWFyaWEgQVYvQUMgVG9yaW5vIC0gTWlsYW5vIG5lbCBDb211bmUgZGkgR3JlZ2dpbyAgW1JGSS1EUFItRFRQX1RPLklOR1xQRUNcUFwyMDE5XDAwMDUyNDRd=?=";
// Get bytes from string 
byte[] byteArray = Base64.decodeBase64(rawvalue.getBytes());
   
// Print the decoded array 
System.out.println(Arrays.toString(byteArray));
   
// Print the decoded string  
String decodedString = new String(byteArray); 
System.out.println(rawvalue + " = " + decodedString);
```

**Mail server:**
 - Protocol being used: imap

**JavaMail version:**
- 1.5.6

**Comment by bshannon** [comment]
I can't reproduce this problem.  Do you have a simple program that reproduces it?
Are you using IMAP to read the message?  If so, please post the JavaMail debug output.

**Comment by rgambelli** [comment]
You can simply reproduce it with this code:

```
public static void main(String[] args) {
        String subject = "=?UTF-8?B?UmlmLiBQcmF0LjogNDhBVi04MDc5IEF0dHJhdmVyc2FtZW50byB0ZWxlZm9uaWNvIHN1cGVyaW9yZSwgaW4gY2F2ZWRpbyBlc2lzdGVudGUsIGNvbiBjYXZpIGEgRi5PLiBhbCBrbSA2NCs0MjAgZGVsbGEgbGluZWEgZmVycm92aWFyaWEgQVYvQUMgVG9yaW5vIC0gTWlsYW5vIG5lbCBDb211bmUgZGkgR3JlZ2dpbyAgW1JGSS1EUFItRFRQX1RPLklOR1xQRUNcUFwyMDE5XDAwMDUyNDRd=?=";
        try {
            System.out.println(MimeUtility.decodeText(subject));
        } catch (UnsupportedEncodingException ex) {
            ex.printStackTrace();
        }
    }
```
While if you set this property:

`System.setProperty("mail.mime.base64.ignoreerrors", "true");`

and re-run, the resulting text appear decoded.

So I suppose it's all ok, I mean it is a real not well encoded text, if you confirm this then this is a false issue I think.
Sorry, when I open this issue I didn't know that system property

**Comment by bshannon** [comment]
Yes, the text is incorrectly encoded.  The decodeText method ignores any
such errors and just returns the original string.  I can't get it to throw the
DecodingException you describe above in any case.

**Comment by rgambelli** [comment]
That exception is internally catched, so you can see it only debugging BASE64DecoderStream, anyway thanks for your confirm
