### ISSUE TITLE
change from javax.* to jakarta.*

### ISSUE THREAD

**Issue by ederks85** [eclipse-ee4j/mail#406]
**Is your feature request related to a problem? Please describe.**
"javax" needs to be renamed to "jakarta" for Jakarta EE 9 release

**Describe the solution you'd like**
Every mention of "javax" in code and comments replaced with "jakarta"

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by ederks85** [comment]
Please follow https://github.com/eclipse-ee4j/mail/pull/410 for progress on my part

**Comment by bshannon** [comment]
This work has been done.
