### ISSUE TITLE
NPE com.sun.mail.pop3.POP3Store.close

### ISSUE THREAD

**Issue by M66B** [eclipse-ee4j/mail#413]
**Describe the bug**
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void java.net.Socket.close()' on a null object reference
        at com.sun.mail.pop3.Protocol.close(SourceFile:358)
        at com.sun.mail.pop3.Protocol.quit(SourceFile:348)
        at com.sun.mail.pop3.POP3Store.close(SourceFile:347)
        at com.sun.mail.pop3.POP3Store.close(SourceFile:338)
```
**To Reproduce**
*simpleCommandStart* throws an *IOException* when the socket is null, causing *quit* to call *close* in finally and close assumes socket is not null.

Note that the caller already checks for *isConnected*.

**Expected behavior**
No NPE

**Smartphone (please complete the following information):**
 - Device: Pixel 3a XL
 - OS: Android 10
 - Browser: N/A
 - Version: 1.6.5-SNAPSHOT

**Possible solutions**

* check socket in finally of *quit*
* check socket on *close*
* check socket in *isConnected*

**Comment by M66B** [comment]
@bshannon thanks for fixing this.

**Comment by M66B** [comment]
@bshannon can we get a new (snapshot) release with this and other changes/fixes?

**Comment by bshannon** [comment]
The Eclipse Jenkins build system seems to be broken.  As soon as it's fixed
I'll push out a SNAPSHOT release.

**Comment by bshannon** [comment]
A new 1.6.5-SNAPSHOT release should be available now.
Let me know how it works for you.

**Comment by bshannon** [comment]
Sorry, never mind, it looks like my deployment is failing silently.
There are snapshots available, but they're all old.

**Comment by M66B** [comment]
@bshannon too bad :-(

**Comment by bshannon** [comment]
Ok, this is working now, but note that the snapshots are in a different repo since we added
a Nexus repository just for Jakarta.  You'll need to add something like this to you ~/.m2/settings.xml:

```
    <profiles>
        <!-- to allow loading Jakarta snapshot artifacts -->
        <profile>
            <id>jakarta-snapshots</id>
            <pluginRepositories>
                <pluginRepository>
                    <id>jakarta-snapshots</id>
                    <name>Jakarta Snapshots</name>
                    <snapshots>
                        <enabled>true</enabled>
                        <updatePolicy>always</updatePolicy>
                        <checksumPolicy>fail</checksumPolicy>
                    </snapshots>
                    <url>https://jakarta.oss.sonatype.org/content/repositories/snapshots/</url>
                    <layout>default</layout>
                </pluginRepository>
            </pluginRepositories>
        </profile>
    </profiles>
```

And then when you build use `mvn -Pjakarta-snapshots ...`.

If you want the plugin repository to be enabled all the time so you don't need the -P, add:

```
    <activeProfiles>
        <activeProfile>jakarta-snapshots</activeProfile>
    </activeProfiles>
```

Let me know if that works for you.

**Comment by M66B** [comment]
@bshannon it was easy to update the snapshot in Android studio ;-)

**Comment by M66B** [comment]
@bshannon I haven't seen this issue anymore, so it is likely fixed :-)

**Comment by bshannon** [comment]
Thanks for testing!
