### ISSUE TITLE
Unexpected behavior for MimeBodyPart.isMimeType

### ISSUE THREAD

**Issue by ganzm** [eclipse-ee4j/mail#414]
**Describe the bug**

javadoc for `MimeBodyPart.isMimeType ` states that if mimeType subtype is `*` then subtype comparison is ignored.

This is rather unintuitive considering the following code snippet.

```
MimeBodyPart part1 = new MimeBodyPart();
part1.setHeader("Content-Type", "application/*");
Assert.assertFalse(part1.isMimeType("application/zip")); // test fails

MimeBodyPart part2 = new MimeBodyPart();
part2.setHeader("Content-Type", "application/zip");
Assert.assertTrue(part2.isMimeType("application/*")); // test succeeds
```

**To Reproduce**
1. Compile the above posted code snippet
2. Assert fails

**Expected behavior**
Both assert succeed.

**System:**
 - OS: Windows, Ubuntu
 - Version 1.6.4

**Comment by bshannon** [comment]
It's referring to the mimeType parameter to the method, not the value in the header.
Obviously a subtype of "*" in an actual header would be illegal.
