### ISSUE TITLE
OAuth2 support for POP3

### ISSUE THREAD

**Issue by pdrygasa** [eclipse-ee4j/mail#416]
**Is your feature request related to a problem? Please describe.**
Industry leaders are retiring Basic Authentication. Later this year, we will observe a complete switch-off of it in services such as Microsoft's Exchange Online or Google's G Suite. Given it's the only authentication method offered by Jakarta Mail for the POP3 protocol, it means that the mail clients, servers and similar software in the Java ecosystem will cease to be able to connect to these leading services.

**Describe the solution you'd like**
Just like for IMAP and SMTP, it would be great to have an out-of-the-box OAuth2 support for the POP3 protocol. Given that Jakarta Mail offers 2 ways to connect with the former protocols via OAuth2 (through SASL and built-in mechanisms), it would ideally do the same for POP3.

**Additional context**
Microsoft's statement on retiring Basic Authentication. Also, an announcement that they're in the process of brining OAuth2 support for POP3 to Exchange Online.
https://developer.microsoft.com/en-us/office/blogs/end-of-support-for-basic-authentication-access-to-exchange-online-apis-for-office-365-customers/

Google's announcement
https://gsuiteupdates.googleblog.com/2019/12/less-secure-apps-oauth-google-username-password-incorrect.html

Mail.dll (sort of a Jakarta Mail's counterpart in .NET) introduction of POP3 OAuth2 support as a reponse to the abovementioned deprecations
https://www.limilabs.com/qa/3641/oauth-supported-before-microsoft-deadline-require-office

**Comment by bshannon** [comment]
This took longer than I expected, but I think I've got it working.
I'll push a [1.6.5-SNAPSHOT release](https://eclipse-ee4j.github.io/mail/#Development_Releases) next.  Please try it out and
let me know if it works for you.  I tested it with Gmail and it works
for me.

**Comment by pdrygas** [comment]
That's amazing news for us @bshannon I will test the SNAPSHOT ASAP. I'd say I should be back with the results at the beginning of next week (our OAuth 2.0 integration is not fully operational yet so testing will take longer than it should)

**Comment by bshannon** [comment]
Any progress on testing this yet?

**Comment by mwalas-atlassian** [comment]
Hello bshannon, we've started working on it today, had a little delay. We should have an answer within a few working days.

**Comment by mwalas-atlassian** [comment]
Hello again, we've confirmed that your changes work. Thanks!

**Comment by bshannon** [comment]
Excellent!  Thanks for testing!

**Comment by mwalas-atlassian** [comment]
Hello once again

When do you plan on releasing a new version with the POP & OAuth changes?

**Comment by bshannon** [comment]
Real soon now.  Possibly even today.

**Comment by craigsha** [comment]
Hi @bshannon, 

I opened a bug/question related to this - would you be able to help us understand if this is an issue within the jakarta library, or with how Microsoft are authenticating the connection with POP3? 

https://github.com/eclipse-ee4j/mail/issues/461

Thanks,
Craig.
