### ISSUE TITLE
Deliver Jakarta Mail Specification Version update for Jakarta EE 9

### ISSUE THREAD

**Issue by kwsutter** [eclipse-ee4j/mail#417]
**Is your feature request related to a problem? Please describe.**
Jakarta EE 9 is the next major release, with the main focus of moving from the ```javax``` namespace to the ```jakarta``` namespace.

**Describe the solution you'd like**
This issue will be used to track the progress of this work effort via the [Jakarta EE 9 Project board](https://github.com/orgs/eclipse-ee4j/projects/17).

**Additional context**
[Jakarta EE Specification Process](https://jakarta.ee/about/jesp/)
[Eclipse Project Handbook](https://www.eclipse.org/projects/handbook/#release)
[Eclipse Release Record for Jakarta EE 9](https://projects.eclipse.org/projects/ee4j.jakartaee-platform/releases/9)

**ToDo**
- [x] **[Create Eclipse Release Record](https://www.eclipse.org/projects/handbook/#pmi-commands-release) in your respective Jakarta Specification Project.**
 Most Component Release Records will just reference the [Jakarta EE 9 Platform Release Plan](https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee9/JakartaEE9ReleasePlan).  But, if your Component deviates at all from the Platform Release Plan, then a description of the changes will be required in the Release Record.
- [x] **Initiate a ballot for your Jakarta Release Record/Plan.**
 Again, if your component is only doing the required minimum as defined by the [Jakarta EE 9 Platform Release Plan](https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee9/JakartaEE9ReleasePlan), then no separate ballot is required.  You are already approved.  But, if your component deviates from the Platform Release Plan, then you will need to initiate your own ballot as defined by the [Jakarta EE Specification Process](https://jakarta.ee/about/jesp/).
- [x] **Jakarta-ize your Specification document (if applicable)**
 Many of the Jakarta EE components now have the source for their Specification documents.  It is strongly recommended that these Specification documents are properly updated to represent Jakarta EE instead of Java EE.  Some [helpful instructions are documented](https://github.com/jakartaee/specification-committee/blob/master/steps_javaee_to_jakartaee.adoc) here.
- [x] **javax -> jakarta Spec updates**
 If your component has Specification source, then all javax package references need to be updated to use jakarta package references.
- [x] **javax -> jakarta API updates**
 Your component APIs need to move from using the javax namespace to using the jakarta namespace.
- [x] **Release Candidate (RC) of Jakarta API in Maven Central**
 A Release Candidate of your component API should be pushed to Maven Central as soon as humanly possible.  This will allow other dependent components to utilize your APIs as they are updating their APIs.  Multiple revisions of these Release Candidate APIs are allowed (and probably expected) during the development cycle.
- [x] **javax -> jakarta TCK updates**
 Your component TCK needs to be updated to use the jakarta namespace.
- [x] **javax -> jakarta Compatible Implementation updates**
 Your compatible implementation that will be used to demonstrate completeness of the Specification needs to be updated to use the jakarta namespace.
- [x] **Final Jakarta API available in Staging Repo**
 When ready, your final version of the API needs to be staged to get ready for the PR review and approvals.
- [x] **Draft Specification and Apidoc PRs ready for review**
 Like we did for Jakarta EE 8, draft PRs need to be created and reviewed in preparation for the final ballots.
- [x] **Release Review Ballot started**
 Each Jakarta EE component will need to initiate a separate Release Review ballot after proper reviewing has completed.  To be clear, there will not be a blanket Release Review for all of Jakarta EE 9 like we did for the Plan Review.  Each component needs a separate Release Review.

**Comment by neuwerk** [comment]
@bshannon It looks the the 2.0.0 branch has the package updates from javax.* to jakarata.* done already. I was going to offer to help with that, but don't want to duplicate any work you've already done. Do you have a specific item on the list I can help with?

**Comment by bshannon** [comment]
Nope, I believe it's all done.  TCK too.  I'm in the process of updating the spec document text.  Thanks anyway.

**Comment by kwsutter** [comment]
Just noticed that the Jakarta Mail Specification is actually housed in the [mail-spec repository](https://github.com/eclipse-ee4j/mail-spec).  Since the Spec work is probably more time consuming, not sure if this Issue should transfer to that repo?  Or, now that we have think linked via this comment, maybe we can leave it here.  No preference, just an observation as I was trying to determine the state of the Specification conversion.

**Comment by kwsutter** [comment]
@bshannon Any outlook for a Milestone/RC API artifact in Maven Central?  Thanks!

**Comment by bshannon** [comment]
I've been running into one problem after another with getting this published.
Right now I'm running into a problem where it's trying to publish to oss.sonatype.org
(and failing, of course) even though I'm using the new parent pom and running with
the staging profile that should cause it to publish to the jakarta.oss.sonatype.org repo.
I'm still trying to figure out why this isn't working...

**Comment by bshannon** [comment]
Ok, I think I finally figured it out.  2.0.0-RC1 should appear momentarily.

**Comment by kwsutter** [comment]
Looking for an update on the status of the JakartaMail Final Specification PR.  If we're going to make the [Sept deliverable goal](https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee9/JakartaEE9#jakarta-ee-9-schedule), then this Wave 2 Specification needs to be ready for final ballot by Monday, July 26.  Which means that the Specification PRs should already be created and under a "mentorship" review.  Can I ask what the plans are for this Specification?  Thanks!

**Comment by lukasj** [comment]
Done
