### ISSUE TITLE
NPE in MailHandler::isLoggable

### ISSUE THREAD

**Issue by anthonyvdotbe** [eclipse-ee4j/mail#421]
**Describe the bug**
The test `MailHandlerTest::testIsLoggable` fails with an NPE in `MailHandler::isLoggable`

**To Reproduce**
1. `mvn clean verify` (at commit 7ad9fe3999883a0f8a4bb30fab9ddcbf8926838e) with Maven 3.6.2 and Java 11 (Azul Zulu 11.0.6+10)

**Expected behavior**
The project builds successfully.

**Actual behavior**
The following NPE is thrown. From the stack trace, this seems logical: the test passes a `null` record, and `MailHandler::isLoggable` does `record.getLevel()`.

Not sure how this should be resolved: should `MailHandler::isLoggable` be able to deal with `null` records? Or is the `MailHandlerTest::testIsLoggable` test broken?

On another note: at first sight, none of this code was touched recently, so I don't understand why this hasn't been noticed before?

````
java.lang.NullPointerException
        at com.sun.mail.util.logging.MailHandler.isLoggable(MailHandler.java:579)
        at com.sun.mail.util.logging.MailHandlerTest.testLoggable(MailHandlerTest.java:457)
        at com.sun.mail.util.logging.MailHandlerTest.testIsLoggable(MailHandlerTest.java:439)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at ...
````

**Comment by jmehrens** [comment]
This one has been on my list to fix for a while now.  I'll create a patch for this.

**Comment by bshannon** [comment]
@jmehrens if you can get a fix for this in the next few days, I can include it in the 1.6.5
release I'm getting ready to make.  (Likely the last 1.6.x release.)  If it's going to take a
lot longer than that, please let me know.  Thanks.

**Comment by jmehrens** [comment]
@bshannon Pull request was created let me know if you run into any problems.

**Comment by jmehrens** [comment]
@bshannon I updated the commit.  Also I forgot to modify the CHANGES.txt so that is now included in the new commit.

**Comment by jmehrens** [comment]
@bshannon Does this patch need to be ported to the 2.0.0 branch?  If so, is the worked under this ticket or a new ticket?

**Comment by bshannon** [comment]
Once I finish the 1.6.5 release, I'll merge the 2.0.0 branch into master and master
will become the branch where the 2.0.0 release is done.  I'm hoping I won't have
to make any 1.6.x releases after that point, but if I do I'll create a maintenance
branch off the 1.6.5 release and do releases from that branch.  At that point we
would need to worry about applying patches to both branches.  But I'm really
hoping that won't be necessary.
