### ISSUE TITLE
Update documentation regarding proxy

### ISSUE THREAD

**Issue by steven-lai** [eclipse-ee4j/mail#424]
**Describe the bug**
Not sure if this is the correct venue for out-of-date documentation.

The documentation at https://eclipse-ee4j.github.io/mail/FAQ#proxy (and https://javaee.github.io/javamail/FAQ#proxy) both mention that "proxy server authentication is not supported." but I believe as of https://github.com/javaee/javamail/pull/331 authentication has been added.

**To Reproduce**
See above

**Expected behavior**
FAQ needs to be updated to include details about proxy server authentication.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Mail server:**
N/A

**Additional context**
N/A

**Comment by bshannon** [comment]
Yes, the per-protocol package javadocs were updated but the FAQ was not.
I've updated the FAQ.
