### ISSUE TITLE
IMAP search misses emails

### ISSUE THREAD

**Issue by oliviercailloux** [eclipse-ee4j/mail#425]
**Describe the bug**
When searching in an IMAP e-mail folder using `RecipientStringTerm` or `RecipientTerm`, some e-mails are not reported whereas they match the search criteria.

**To Reproduce**
The problem can’t be reproduced as is by the reader, as it requires accessing my inbox. But, hopefully, this is a known problem and someone can tell me what’s going on (an extensive search in the issues here and on SO about `RecipientStringTerm` or `RecipientTerm` did not bring anything useful, though). 

The following code reproduces the bug 100% for me. It first retrieves the message number 6068, checks that it is sent to `"olivier.cailloux@dauphine.fr"`. Then it searches for messages sent to `"olivier.cailloux"` (using `RecipientStringTerm`). The message 6068 is among the matches, as expected. Same when searching for messages sent to `"olivier.cailloux@dauphine."`. But when searching for messages sent to `"olivier.cailloux@dauphine.fr"`, no matches are found! And searching for the address of the message 6068 using `RecipientTerm` also fails to find that message.

```
final Properties props = new Properties();
props.setProperty("mail.store.protocol", "imap");
props.setProperty("mail.host", "outlook.office365.com");
props.setProperty("mail.imap.connectiontimeout", "2000");
props.setProperty("mail.imap.timeout", "60*1000");
props.setProperty("mail.imap.connectionpooltimeout", "10");
props.setProperty("mail.user", "ocailloux@dauphine.fr");
props.setProperty("mail.imap.ssl.enable", "true");
props.setProperty("mail.imap.ssl.checkserveridentity", "true");
final Session session = Session.getInstance(props);
try (Store store = session.getStore()) {
	LOGGER.info("Connecting.");
	store.connect(EMailer.USERNAME, getToken());
	try (Folder folder = store.getFolder("Éléments envoyés")) {
		folder.open(Folder.READ_ONLY);
		final Message[] messages6068 = folder.getMessages(6068, 6068);
		assertEquals(1, messages6068.length);
		final Message messageToDauphine = messages6068[0];

		final Address[] recipients = messageToDauphine.getRecipients(RecipientType.TO);
		assertEquals(1, recipients.length);
		final InternetAddress recipient = (InternetAddress) recipients[0];
		assertEquals("olivier.cailloux@dauphine.fr", recipient.getAddress());
		LOGGER.info(String.format("Message %s dated %s to %s.", messageToDauphine.getMessageNumber(),
				messageToDauphine.getSentDate(), recipient));
		{
			final Message[] messagesToPartialRecipientStringTerm = folder
					.search(new RecipientStringTerm(RecipientType.TO, "olivier.cailloux"));
			/** Succeeds */
			assertNotEquals(0, messagesToPartialRecipientStringTerm.length);
			assertEquals(1, Arrays.stream(messagesToPartialRecipientStringTerm)
					.filter(m -> m.getMessageNumber() == 6068).count());
		}
		{
			final Message[] messagesToPartialRecipientStringTerm = folder
					.search(new RecipientStringTerm(RecipientType.TO, "olivier.cailloux@dauphine."));
			/** Succeeds */
			assertNotEquals(0, messagesToPartialRecipientStringTerm.length);
			assertEquals(1, Arrays.stream(messagesToPartialRecipientStringTerm)
					.filter(m -> m.getMessageNumber() == 6068).count());
		}
		{
			final Message[] messagesToThatRecipientStringTerm = folder
					.search(new RecipientStringTerm(RecipientType.TO, "olivier.cailloux@dauphine.fr"));
			/** Fails! */
			assertNotEquals(0, messagesToThatRecipientStringTerm.length);
		}
		{
			final Message[] messagesToThatRecipient = folder
					.search(new RecipientTerm(RecipientType.TO, recipient));
			/** Also fails. */
			assertNotEquals(0, messagesToThatRecipient.length);
		}
	}
}
```

**Expected behavior**
The unit test should pass instead of failing at the places indicated above.

**Mail server:**
 - IMAP
 - Microsoft Exchange (I think)
 - Mail service URL: outlook.office365.com

**Comment by bshannon** [comment]
Most likely this is a bug in the IMAP server.

Please provide the [JavaMail debug output](https://javaee.github.io/javamail/FAQ#debug), which will allow us to confirm that JavaMail
is sending the expected command and the server's response does not include the message
that should be matched.

**Comment by bshannon** [comment]
Also, you could try copying the message to another mailbox on another server, e.g., Gmail,
and test that your program works as expected there.

**Comment by bshannon** [comment]
Since this is most likely a bug in the mail server, I'm closing this issue.
If you provide that additional information requested above, please feel
free to reopen this issue.  Thanks.

**Comment by oliviercailloux** [comment]
Thanks for the pointers.

Turning debug on indicates that JavaMail seems to report the correct commands (at least, AFAICT: I am not knowledgeable of the IMAP spec).

```
DEBUG: JavaMail version 1.6.3
DEBUG: successfully loaded resource: /META-INF/javamail.default.address.map
DEBUG: getProvider() returning javax.mail.Provider[STORE,imap,com.sun.mail.imap.IMAPStore,Oracle]
DEBUG IMAP: mail.imap.fetchsize: 16384
DEBUG IMAP: mail.imap.ignorebodystructuresize: false
DEBUG IMAP: mail.imap.statuscachetimeout: 1000
DEBUG IMAP: mail.imap.appendbuffersize: -1
DEBUG IMAP: mail.imap.minidletime: 10
DEBUG IMAP: closeFoldersOnStoreFailure
00:45:57.170 [main] INFO  i.g.o.email.EmailerTests - Connecting.
DEBUG IMAP: trying to connect to host "outlook.office365.com", port 993, isSSL true
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.sun.mail.util.SocketFetcher (file:/home/olivier/.m2/repository/com/sun/mail/jakarta.mail/1.6.3/jakarta.mail-1.6.3.jar) to method sun.security.util.HostnameChecker.getInstance(byte)
WARNING: Please consider reporting this to the maintainers of com.sun.mail.util.SocketFetcher
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
* OK The Microsoft Exchange IMAP4 service is ready. [TABPADIAUAAyADYANQBDAEEAMAAxADEAMgAuAEcAQgBSAFAAMgA2ADUALgBQAFIATwBEAC4ATwBVAFQATABPAE8ASwAuAEMATwBNAA==]
A0 CAPABILITY
* CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
A0 OK CAPABILITY completed.
DEBUG IMAP: AUTH: PLAIN
DEBUG IMAP: AUTH: XOAUTH2
DEBUG IMAP: protocolConnect login, host=outlook.office365.com, user=ocailloux@dauphine.fr, password=<non-null>
DEBUG IMAP: AUTHENTICATE PLAIN command trace suppressed
DEBUG IMAP: AUTHENTICATE PLAIN command result: A1 OK AUTHENTICATE completed.
A2 CAPABILITY
* CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS MOVE ID UNSELECT CLIENTACCESSRULES CLIENTNETWORKPRESENCELOCATION BACKENDAUTHENTICATE CHILDREN IDLE NAMESPACE LITERAL+
A2 OK CAPABILITY completed.
DEBUG IMAP: AUTH: PLAIN
DEBUG IMAP: AUTH: XOAUTH2
DEBUG IMAP: connection available -- size: 1
A3 EXAMINE "&AMk-l&AOk-ments envoy&AOk-s"
* 6729 EXISTS
* 1 RECENT
* FLAGS (\Seen \Answered \Flagged \Deleted \Draft $MDNSent)
* OK [PERMANENTFLAGS ()] Permanent flags
* OK [UIDVALIDITY 11] UIDVALIDITY value
* OK [UIDNEXT 11523] The next unique identifier value
A3 OK [READ-ONLY] EXAMINE completed.
A4 FETCH 6068 (ENVELOPE INTERNALDATE RFC822.SIZE)
* 6068 FETCH (ENVELOPE ("Mon, 2 Dec 2019 14:46:46 +0000" "Re: Jurys M1 apprentissage" (("Olivier Cailloux" NIL "olivier.cailloux" "dauphine.fr")) NIL NIL (("Olivier Cailloux" NIL "olivier.cailloux" "dauphine.fr")) NIL (("Florian [redacted])) "<8907f2be87efce69cff85896c9a6453906b43bac.camel@dauphine.fr>" "<ed20403625b1305a3ec346f3ec74a772daa94197.camel@dauphine.fr>") INTERNALDATE "02-Dec-2019 15:46:46 +0100" RFC822.SIZE 11647)
A4 OK FETCH completed.
00:46:00.931 [main] INFO  i.g.o.email.EmailerTests - Message 6068 dated Mon Dec 02 15:46:46 CET 2019 to Olivier Cailloux <olivier.cailloux@dauphine.fr>.
A5 SEARCH TO olivier.cailloux ALL
* SEARCH 174 198 200 228 295 310 962 963 1316 2086 2753 2804 2833 2953 3777 4078 4264 4673 4677 4724 4725 5207 5278 5279 5288 5352 5357 5513 5595 5596 5597 5598 5599 5615 5616 5617 5618 5619 5620 5621 5622 5623 5625 5627 5628 5629 5746 6041 6068 6453 6454 6455 6456 6542 6545 6558 6578 6579 6580 6650 6655 6656 6657 6658 6659 6660 6661 6662 6663 6664 6665 6666 6667 6668 6669 6670 6671 6672 6673 6674 6675 6676 6677 6678 6679 6680 6681 6682 6683 6710 6711 6712
A5 OK SEARCH completed.
A6 SEARCH TO olivier.cailloux@dauphine. ALL
* SEARCH 295 962 963 2086 2753 2804 2833 2953 3777 4078 4264 4673 4677 4724 4725 5352 5357 5513 5746 6041 6068 6453 6454 6455 6456 6545 6578
A6 OK SEARCH completed.
A7 SEARCH TO olivier.cailloux@dauphine.fr ALL
* SEARCH
A7 OK SEARCH completed.
A8 SEARCH TO "Olivier Cailloux <olivier.cailloux@dauphine.fr>" ALL
* SEARCH
A8 OK SEARCH completed.
A9 CLOSE
A9 OK CLOSE completed.
DEBUG IMAP: added an Authenticated connection -- size: 1
DEBUG IMAP: IMAPStore cleanup, force false
A10 LOGOUT
* BYE Microsoft Exchange Server IMAP4 server signing off.
A10 OK LOGOUT completed.
DEBUG IMAP: IMAPStore cleanup done
```

Also, I have tried the following, directly with openssl, and the problem appears as well:
```
A SEARCH TO olivier.cailloux@dauphine. ALL
* SEARCH 295 962 963 2086 2753 2804 2833 2953 3777 4078 4264 4673 4677 4724 4725 5352 5357 5513 5746 6041 6068 6453 6454 6455 6456 6545 6578
A SEARCH TO olivier.cailloux@dauphine.f ALL
* SEARCH
```

So it is most probably unrelated to JavaMail (unless I misunderstand the specification).

Do you think there is any chance of finding a bug report about this on the web? This is Microsoft exchange, so I must not be the only person encountering it, but Google is not much helpful. I only found [this](https://stackoverflow.com/a/51523115), but the behavior I observe is not exactly similar to the one described there.

If there is any chance of getting the bug fruitfully known to some responsible developers, I’ll be happy to do it. But as an individual developer with no specific connexions to Microsoft, I suppose the odds are stacked against me. 

The JavaMail FAQ indicates: “The best approach when running into server bugs of this sort is to contact the vendor of the server and get them to fix their product. Contact javamail_ww@oracle.com and we'll help you pinpoint the problem so that you can report it to the server vendor.” Is this serious?

**Comment by bshannon** [comment]
> So it is most probably unrelated to JavaMail (unless I misunderstand the specification).

No, you're right, it looks like a server bug.

> Do you think there is any chance of finding a bug report about this on the web? This is Microsoft exchange, so I must not be the only person encountering it, but Google is not much helpful. I only found [this](https://stackoverflow.com/a/51523115), but the behavior I observe is not exactly similar to the one described there.

I don't think Microsoft makes their bug reports publicly available.

> If there is any chance of getting the bug fruitfully known to some responsible developers, I’ll be happy to do it. But as an individual developer with no specific connexions to Microsoft, I suppose the odds are stacked against me.

You probably need to have a support contract with Microsoft in order to file a bug report.

> The JavaMail FAQ indicates: “The best approach when running into server bugs of this sort is to contact the vendor of the server and get them to fix their product. Contact [javamail_ww@oracle.com](mailto:javamail_ww@oracle.com) and we'll help you pinpoint the problem so that you can report it to the server vendor.” Is this serious?

Yup, and you've mostly figured it out yourself.  You have everything you need in
the debug output to file a bug report.  How you report it to the server vendor is
outside our control.

**Comment by oliviercailloux** [comment]
I hope I don’t abuse your time with one last question about this. I want to switch, for my particular application, to using a mail server which implements the IMAP search API correctly (or, let’s say, as correctly as can be reasonably asked). I am talking about using the basic RFC IMAP search capabilities, without server extensions, e.g., for searching for all e-mails sent to a specific address, and combining simple criteria using some OR and AND combinations.

You suggested trying with Gmail here above, but the [Javamail FAQ](https://javaee.github.io/javamail/FAQ#gmailsearch) mentions that it “does not fully support all IMAP features”. The link provided for more information in the FAQ is not helpful, I suppose its content changed, and I couldn’t find precise information on the internet about this. Is there more information available on the extent to which Gmail supports IMAP search (without its [server extensions](https://developers.google.com/gmail/imap/imap-extensions), I mean)?

Would you possibly suggest some e-mail service providers that are known to implement the RFC specifications (about) correctly?

I think that an answer to this question would be a good candidate for an entry in the Javamail FAQ!

**Comment by bshannon** [comment]
There's more information about Gmail on the [Jakarta Mail web site](https://eclipse-ee4j.github.io/mail/Gmail).  Beyond that, you'll need to ask Google.

There's lots and lots of mail server products and service available.  I'm not about
to get into the business of comparing or recommending them.  Unfortunately,
IMAP conformance is usually not one of the key buying decisions.  There seems
to be an inverse correlation between IMAP conformance and popularity, generally
because popular IMAP mail clients set the bar so low.

If you do an evaluation of IMAP servers, please publish it and I'd be happy to link to it!

**Comment by oliviercailloux** [comment]
> If you do an evaluation of IMAP servers, please publish it and I'd be happy to link to it!

Thanks a lot for the reply. This would constitue a perfect student project, I keep it in mind (note for anyone reading this: don’t hold your breath, it will not happen this year or the next one).

I guess I’ll go with Gmail, in the meantime, as I don’t have resources now for a proper search, and as they do [seem](https://stackoverflow.com/a/23240085) (or did seem?) to take IMAP at least a bit seriously, compared to other big names.

May I suggest to replace the outdated link in the [FAQ](https://javaee.github.io/javamail/FAQ#gmailsearch) with a link to the [Jakarta Mail web site](https://eclipse-ee4j.github.io/mail/Gmail)?
