### ISSUE TITLE
Dependency on com.sun.mail?

### ISSUE THREAD

**Issue by kwsutter** [eclipse-ee4j/mail#426]
**Describe the bug**
When creating the Platform API jar file, there is this reference in the pom.xml...  Is this dependency cleaned up yet?  Or, is this still required?

```
        <!--
            Using com.sun.mail:jakarta.mail instead of
            jakarta.mail:jakarta.mail-api because jakarta.mail has a
            dependency on com.sun.mail classes, but the pom does
            not bring in the dependency.
        -->
        <dependency>
            <groupId>jakarta.mail</groupId>
            <artifactId>jakarta.mail-api</artifactId>
            <version>${jakarta.mail-api.version}</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.sun.mail</groupId>
            <artifactId>jakarta.mail</artifactId>
            <version>${jakarta.mail-api.version}</version>
            <optional>true</optional>
        </dependency>
```

**To Reproduce**
1. Look at pom.xml in the jakartaee-api subdirectory (jakartaee-api repo)

I did find this Issue #409 that looks to be related, but it looks to be more specific to module content rather than the dependency.  If this dependency is not cleaned up yet, will it eventually be cleaned up for Jakarta EE 9?

**Comment by bshannon** [comment]
It's still required, for the same reason as the similar faces requirement that
Romain explained.
