### ISSUE TITLE
Sources jar is "empty" for jakarta.mail:jakarta.mail-api:2.0.0-RC1

### ISSUE THREAD

**Issue by kwsutter** [eclipse-ee4j/mail#427]
**Describe the bug**
The sources jar for jakarta.mail:jakarta.mail-api:2.0.0-RC1 is "empty".  It contains some metadata and a populated `javax` tree, but the `jakarta` source tree is empty.

**To Reproduce**
Download the sources jar file:  https://search.maven.org/remotecontent?filepath=jakarta/mail/jakarta.mail-api/2.0.0-RC1/jakarta.mail-api-2.0.0-RC1-sources.jar

Look at the content of the `jakarta` subdirectory.  You'll find the other subdirectories, but none of the source files exist.  They do exist in the `javax` tree.

**Expected behavior**
In order for the build of the jakartaee-api to work properly, we need the source files for all of the API projects.

**Additional context**
This is in support of Jakarta EE 9.  I'm trying to build a Milestone/RC API artifact for the Jakarta EE 9 Platform and Web Profile.

**Comment by kwsutter** [comment]
FYI, @bshannon...  The commit you referenced above may fix some missing javadoc, but it doesn't resolve the missing source code.  The RC2 artifact still provides an empty `jakarta` source tree in the jakarta.mail-api-2.0.0-RC2-sources.jar file.

**Comment by bshannon** [comment]
Grumble.  Yes, one more thing I forgot to fix.

**Comment by bshannon** [comment]
2.0.0-RC3 (only in staging) should fix it.

**Comment by kwsutter** [comment]
> 2.0.0-RC3 (only in staging) should fix it.

Will this eventually be released to Maven Central?  Or, did you want me to test it out before you push it?

**Comment by bshannon** [comment]
Please test it.  I will probably make further changes before releasing it to Maven Central.
(I don't think there's a point in releasing lots of RC versions if we can work with the
version in the staging repo.)

**Comment by kwsutter** [comment]
@bshannon  Still no worky...  https://jakarta.oss.sonatype.org/service/local/repo_groups/staging/content/jakarta/mail/jakarta.mail-api/2.0.0-RC3/jakarta.mail-api-2.0.0-RC3-sources.jar has an empty jakarta source tree...

**Comment by bshannon** [comment]
I don't know what that location is, but it looks fine here: https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/mail/jakarta.mail-api/2.0.0-RC3/jakarta.mail-api-2.0.0-RC3-sources.jar

**Comment by pzygielo** [comment]
@bshannon 

```
$ sha1sum jakarta.mail-api-2.0.0-RC3.jar jakarta.mail-api-2.0.0-RC3-sources.jar 
48f96615f5c862b97b4a0a2f43081c5ac587d495  jakarta.mail-api-2.0.0-RC3.jar
41f7687700ed2e4d0d2ac5eccf81338fdaa635dc  jakarta.mail-api-2.0.0-RC3-sources.jar
```
```
$ jar tf jakarta.mail-api-2.0.0-RC3.jar | grep jakarta
[...]
jakarta/mail/event/MailEvent.class
jakarta/mail/event/TransportEvent.class
jakarta/mail/event/FolderEvent.class
jakarta/mail/event/ConnectionListener.class
jakarta/mail/StreamLoader.class
jakarta/mail/Store.class
jakarta/mail/EventQueue.class
jakarta/mail/Session.class
jakarta/mail/Address.class
jakarta/mail/Service.class
[...]
$
```
vs.
```
$ jar tf jakarta.mail-api-2.0.0-RC3-sources.jar | grep jakarta
jakarta/
jakarta/mail/
jakarta/mail/event/
jakarta/mail/search/
jakarta/mail/internet/
jakarta/mail/util/
$
```

**Comment by pzygielo** [comment]
Probably because only package declarations in `*.java`s were migrated to `jakarta.mail`, but files remain in `src/main/java/javax/mail/...` directories.

**Comment by bshannon** [comment]
Wow, ok, either git screwed up, or, more likely, I screwed up and forgot to
rename the javax directory to jakarta.  It's amazing that everything compiled
and all the tests passed including the TCK with the source files being in the
wrong directory!

Ok, this time for sure.  New 2.0.0-RC3 staged and checked.  Let me know of
any more problems.

**Comment by kwsutter** [comment]
Woohoo!  Success, @bshannon!  Go ahead and push this RC3 out to Maven Central.  Thanks!
