### ISSUE TITLE
Maven package/install does not pick the change

### ISSUE THREAD

**Issue by venkatsc** [eclipse-ee4j/mail#431]
**Describe the bug**
Changed file `mail/src/main/java/javax/mail/internet/MimeMessage.java` and built jar. The built jar does not contain the change.

**To Reproduce**
1. Go to `mail/src/main/java/javax/mail/internet/MimeMessage.java` and edit some code.
2. Build (mvn clean install/package)
3. Decompile built jakarta.mail-1.6.5-sources.jar (change present here) and jakarta.mail-1.6.5.jar (change is not seen here)
4. Goto compiled classes and decompile `javax/mail/internet/MimeMessage.class` (change is present here)

**Expected behavior**
Jar should be built with recently compiled classes

**Additional context**
```jar cvf  jakarta.mail-1.6.5.jar -C mail/mail/class . ``` worked fine

**Comment by lukasj** [comment]
the build during package phase creates file named `jakarta.mail.jar` (the name is without version number) in the project's target folder, so it is unclear to me from where the `jakarta.mail-1.6.5.jar` is being taken.

I followed given steps and:
* I used `javap` command to verify the content of compiled class
* I have checked the modified version of the edited file is present in the `mail/target/jakarta.mail.jar` file. (after `package`)
* I have checked the modified version of the edited file is present in the `${maven.repo.local}/com/sun/mail/jakarta.mail/1.6.5/jakarta.mail-1.6.5.jar` file. (after `install`)

In the other words, I cannot reproduce the problem using provided steps.

I believe that the cause of this is wrong jar file being inspected. If that is not the case, feel free to reopen with more info.

Thanks!
