### ISSUE TITLE
jsp-api and servlet-api 4P download url mismatch

### ISSUE THREAD

**Issue by vikas2k14** [eclipse-ee4j/mail#464]
Given to understand for jakarta mail 1.6.5 the 4p dependencies jsp-api and servlet-api which are getting pulled/refereed seems to be of CDDL licensed code  which are the old versions. The new versions, like Jakarta Mail, belongs to EPL v2. (See https://github.com/eclipse-ee4j/servlet-api/blob/master/LICENSE.md) and the dependency files shouldn't be mixing J2EE and EE4J libraries; they should only be picking up EE4J code.
please let us know

**Comment by lukasj** [comment]
fixed
