### ISSUE TITLE
Staged jars are compiled JDK 11 and have a OSGI requirement for JavaSE 9

### ISSUE THREAD

**Issue by smillidge** [eclipse-ee4j/mail#465]
**Describe the bug**
Staged Jakarta Mail artifacts are compiled with JDK 11 and the jakarta mail api bundle has this OSGI requirement
`Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=9))"` 

This jar can't be incorporated into GlassFish 6.x

**Comment by lukasj** [comment]
@smillidge try again, please

**Comment by smillidge** [comment]
Confirmed it is fixed and I created https://github.com/eclipse-ee4j/glassfish/pull/23175
