### ISSUE TITLE
Build failure after merge of #466

### ISSUE THREAD

**Issue by pzygielo** [eclipse-ee4j/mail#472]
Unfortunately merged #466 causes build failure:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project imap: Fatal error compiling: invalid flag: --module-path -> [Help 1]
```
with JDK1.8.

I see [build for merge to master](https://ci.eclipse.org/mail/job/mail/job/master/62/) is green, however on close inspection of [console output](https://ci.eclipse.org/mail/job/mail/job/master/62/consoleFull) one can find `[INFO] BUILD FAILURE` there.
Build continues regardless of that, but I have no idea what is CTK-tested then.

Building previous commit fdad7f1 works fine.

**Comment by lukasj** [comment]
Build on jdk8 is no longer supported. The job being pointed to is obsolete, https://ci.eclipse.org/mail/job/mail-build-release/ is the right one

**Comment by pzygielo** [comment]
1. May I suggest to disable https://ci.eclipse.org/mail/job/mail/job/master then? (to save resources + **not notify** github of results)
2. I've checked few recent builds of https://ci.eclipse.org/mail/job/mail-build-release, and all seem to be started manually. Is there a plan for CI for this project?
3. The last build of _the right one_ job https://ci.eclipse.org/mail/job/mail-build-release/47/ seems to: 
   1. be ran against https://github.com/eclipse-ee4j/mail/commit/fdad7f14004ace268f1115693189dc2495fff603, and no new job was executed for changes intruduced in #466
   1. use 
```
JAVA_HOME=/opt/tools/java/oracle/jdk-8/latest
Java version: 1.8.0_202, vendor: Oracle Corporation, runtime: /opt/tools/java/oracle/jdk-8/1.8.0_202/jre
``` 
so I guess it will need some updates.

**Comment by lukasj** [comment]
I do not have commit rights, thus can do nothing with jobs. Someone else will have to do it. My bad, the most up-to date job seems to be https://ci.eclipse.org/mail/job/release-staging/ instead

**Comment by pzygielo** [comment]
> I do not have commit rights, thus can do nothing with jobs. Someone else will have to do it.

Bug 566444 created.
