### ISSUE TITLE
Complete the Release of Mail 2.0

### ISSUE THREAD

**Issue by keilw** [eclipse-ee4j/mail#479]
These are the remaining steps as per the spec-committee guide for the project team to complete to finalise the release of [Mail 2.0](https://github.com/jakartaee/specifications/pull/247):
- [x] promotes api staging release promotes the specification api jars to maven central. An example release job script can be found here https://wiki.eclipse.org/MavenReleaseScript.
- [x] go through the merged jakarta.ee specification website page to verify all the links are valid.
- [x] approve the compatibility request.
- [x] The compatible implementation project/vendor MUST send an email to tck@eclipse.org for approval of the compatible implementation for trademark usage.
- [ ] merge any final release branch as appropriate for the branch management for the project.

**Comment by lukasj** [comment]
final release branch cannot be merged as it would break the history in master, because @Cousjava merged #475 before the merge could happen.

The rest is done, so closing
