### ISSUE TITLE
Superfluous/duplicate comment & declaration in MimeUtility.java

### ISSUE THREAD

**Issue by raphidae** [eclipse-ee4j/mail#486]
While chasing some other issue I happened to look into MimeUtility.java at https://github.com/eclipse-ee4j/mail/blob/master/mail/src/main/java/jakarta/mail/internet/MimeUtility.java#L456

Now, it's been at least 2 decades since I've done anything with java, so my apologies for wasting your time if this is somehow supposed to be like this. 

I noticed a near-duplicate comment block, followed by a duplicate instance/declaration of "public static String encodeText()".

The first starts at line 456 and ends at line 495, the second one is right after it and starts at line 497 and ends at 528.

The second one seems to be the "real" one (since the first one would call itself), and I guess the duplicate/second declaration renders the first one useless/harmless. The first one was probably accidentally left in at some point.

Apologies for not attaching a patch, but as I said, I'm not even 100% sure this is the problem I think it is. I assume anyone familiar with java will see the issue, or lack thereof :)

**Comment by Cousjava** [comment]
The two methods have different signatures, the first is just `encodeText(String text)` while the second has more parameters and is `encodeText(String text, String charset, String encoding)`.

**Comment by raphidae** [comment]
Ah OK. So, overloading a method in java that way is allowed (and useful as the first instance calls the second). 

Shows what I know of java: nothing. Looked like someone accidentally double-pasted a function (or method) to me :) 

Sorry for wasting your time!
