### ISSUE TITLE
How to use the Mail 2.0 on Android

### ISSUE THREAD

**Issue by wangsuicheng** [eclipse-ee4j/mail#487]
api "jakarta.mail:jakarta.mail-api:2.0.0"
api 'com.sun.activation:jakarta.activation:2.0.0'

just need these dependencies in gradle file ?

**Comment by WaltBeMobiled** [comment]
Hi Wang,
After adding , during build I am getting this error, did you have it (max API 30):
> Task :app:checkDebugDuplicateClasses FAILED
Execution failed for task ':app:checkDebugDuplicateClasses'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform jakarta.activation-2.0.0.jar (com.sun.activation:jakarta.activation:2.0.0) to match attributes {artifactType=enumerated-runtime-classes, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: C:\Users\willi\.gradle\caches\modules-2\files-2.1\com.sun.activation\jakarta.activation\2.0.0\f4e7519148dee347c7666f336210deedb8aca09d\jakarta.activation-2.0.0.jar.
         > Failed to transform 'C:\Users\willi\.gradle\caches\modules-2\files-2.1\com.sun.activation\jakarta.activation\2.0.0\f4e7519148dee347c7666f336210deedb8aca09d\jakarta.activation-2.0.0.jar' using Jetifier. Reason: JDOMParseException, message: Error on line 76: The prefix "Xlint" for element "Xlint:all" is not bound.. (Run with --stacktrace for more details.)

**Comment by wangsuicheng** [comment]
I use 1.6.5 version finally @WaltBeMobiled

**Comment by lukasj** [comment]
```
api "com.sun.mail:jakarta.mail:2.0.0"
api 'com.sun.activation:jakarta.activation:2.0.0'
```

is the way to go. `jakarta.mail:jakarta.mail-api` is just an API, it contains no implementation.

**Comment by wangsuicheng** [comment]
> ```
> api "com.sun.mail:jakarta.mail:2.0.0"
> api 'com.sun.activation:jakarta.activation:2.0.0'
> ```
> 
> is the way to go. `jakarta.mail:jakarta.mail-api` is just an API, it contains no implementation.

https://eclipse-ee4j.github.io/mail/Android
