### ISSUE TITLE
mime handling crashes on Android 11 debug build

### ISSUE THREAD

**Issue by slowcar** [eclipse-ee4j/mail#489]
I face a strange issue with the android libraries, using
com.sun.mail:android-mail:1.6.5
com.sun.mail:android-activation:1.6.5

The crash occurs in MailcapCommandMap.java line 601, where a new instance of multipart_mixed is created (also happens with other classes extending handler_base)

If i create a release build, OR enable minify for the debug build, OR run it on Android 10 or lower, the error does not occur.

Stacktrace:
java.lang.VerifyError: Rejecting class com.sun.mail.handlers.text_plain that attempts to sub-type erroneous class com.sun.mail.handlers.handler_base

 Caused by: java.lang.VerifyError: Verifier rejected class com.sun.mail.handlers.handler_base: java.awt.datatransfer.DataFlavor[] com.sun.mail.handlers.handler_base.getTransferDataFlavors() failed to verify: java.awt.datatransfer.DataFlavor[] com.sun.mail.handlers.handler_base.getTransferDataFlavors(): [0x4]  can't resolve returned type 'Unresolved Reference: java.awt.datatransfer.DataFlavor[]' or 'Reference: javax.activation.ActivationDataFlavor[]'

To reproduce, put this code in an Android project and debug it on Android 11 (device or emulator)

_ClassLoader classLoader = getClassLoader();            
Class cl = classLoader.loadClass("com.sun.mail.handlers.multipart_mixed");
Object multipartMixedObject = cl.newInstance();_

I am unsure, if this is an issue with the library, or rather something on Android OS side, in any case, it's not working.
(as our release builds are still working, this is not a really important issue, but one i would like to solve sometime regardless)

**Comment by wkornewald** [comment]
We also have this bug.

**Comment by li42899974** [comment]
i have same problem here !
still do not solve it !
Does anyone can help me ?

**Comment by li42899974** [comment]
roll back the target sdk to 29 will be ok ! i have tried!

**Comment by slowcar** [comment]
@wkornewald the stackoverflow post is from me, i investigated the issue further and decided to post here, as it seems that the problem is caused by the library code.

@li42899974 going back to target sdk 29 is a workaround, but i would prefer a solution within the library.

**Comment by WojciechBemobiled** [comment]
I have the same problem - android 11 does NOT like javax\activation\ActivationDataFlavor.java for some reason. Please Help !!!

**Comment by willDTBM** [comment]
On my side the same problem ... giigle is coming with android 11.

**Comment by eiroj** [comment]
Wanted to report - We have the same issue.

**Comment by NLLAPPS** [comment]
I have the exact same issue too

**Comment by NLLAPPS** [comment]
Here is my crash log

STACK_TRACE=java.lang.VerifyError: Rejecting class com.sun.mail.handlers.text_plain that attempts to sub-type erroneous class com.sun.mail.handlers.handler_base (declaration of 'com.sun.mail.handlers.text_plain' appears in base.apk)
	at java.lang.Class.newInstance(Native Method)
	at yv0.o(SourceFile:9)
	at yv0.a(SourceFile:11)
	at gs.getDataContentHandler(SourceFile:18)
	at gs.writeTo(SourceFile:7)
	at javax.mail.internet.MimeUtility.getEncoding(SourceFile:16)
	at javax.mail.internet.MimeBodyPart.updateHeaders(SourceFile:35)
	at javax.mail.internet.MimeBodyPart.updateHeaders(SourceFile:1)
	at javax.mail.internet.MimeMultipart.updateHeaders(SourceFile:3)
	at javax.mail.internet.MimeBodyPart.updateHeaders(SourceFile:24)
	at javax.mail.internet.MimeMessage.updateHeaders(SourceFile:1)
	at javax.mail.internet.MimeMessage.saveChanges(SourceFile:3)
	at javax.mail.Transport.send(SourceFile:1)
	at zn1.d(SourceFile:30)
	at rz.f(SourceFile:4)
	at rz.e(SourceFile:1)
	at pz$f$a.invokeSuspend(SourceFile:1)
	at ia.resumeWith(SourceFile:3)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:19)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(SourceFile:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(SourceFile:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(SourceFile:4)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:1)
Caused by: java.lang.VerifyError: Verifier rejected class com.sun.mail.handlers.handler_base: java.lang.Object com.sun.mail.handlers.handler_base.getTransferData(p3, js) failed to verify: java.lang.Object com.sun.mail.handlers.handler_base.getTransferData(p3, js): [0xA] 'this' argument 'Reference: p3' not instance of 'Unresolved Reference: javax.activation.ActivationDataFlavor' (declaration of 'com.sun.mail.handlers.handler_base' appears in base.apk)

**Comment by NLLAPPS** [comment]
Issue tracker: https://issuetracker.google.com/issues/172544275

Google says "This is WAI. In SDK 30, we've added a check to ensure the returned type is resolved. java.awt.* and javax.activation.* aren't APIs from Android, so unless you put them in your app, it's expected that they don't resolve. And even though the method at fault may never be executed, in SDK30 we've made things more strict on the return type for correctness.
"

**Comment by NLLAPPS** [comment]
I am able to fix this issue with the following proguard config


-keep class com.sun.mail.imap.** {*;}
-keep class com.sun.mail.smtp.** {*;}
-keep class com.sun.mail.handlers.** {*;}
-keep class javax.activation.** {*;} 

-dontwarn com.sun.mail.**
-dontwarn org.apache.harmony.awt.**
-dontwarn javax.security.sasl.**
-dontwarn java.awt.**
-dontwarn java.beans.**

**Comment by slowcar** [comment]
you are using a proguard config for your debug build that does not use proguard (resp R8)?
I have a similar config, and it helps for the release build, which does not crash. The debug build does, though.

**Comment by NLLAPPS** [comment]
I am applying proguard to all builds because I have bitten more than once with everything working with debug while flood of crashes come in in release builds

**Comment by li42899974** [comment]
> I am able to fix this issue with the following proguard config
> 
> -keep class com.sun.mail.imap.** {_;} -keep class com.sun.mail.smtp.** {_;}
> -keep class com.sun.mail.handlers.** {_;} -keep class javax.activation.** {_;}
> 
> -dontwarn com.sun.mail.**
> -dontwarn org.apache.harmony.awt.**
> -dontwarn javax.security.sasl.**
> -dontwarn java.awt.**
> -dontwarn java.beans.**

i have try your method, but still not work......

**Comment by AlexisDD** [comment]
Same issue here, a fix can solve this or we have to find solutions ourselves ?

**Comment by lukasj** [comment]
I managed to reproduce the problem with 1.6.5. It looks fixed to me by 0175587 as I can no longer reproduce this, so hopefully fixed

**Comment by WaltBeMobiled** [comment]
Hi Lukas, Would it be possible to build the NEW jars for Android with the fix? 
Thanks a lot for your help!

**Comment by lukasj** [comment]
Can I ask someone to try out 1.6.6-SNAPSHOT from the jakarta snapshots repo; https://jakarta.oss.sonatype.org/content/repositories/snapshots just to make sure this is really fixed, please?

**Comment by AlexisDD** [comment]
I just updated to 1.6.6-SNAPSHOT, the bug disappeared but now I got this error : 

W/javax.mail: expected resource not found: {0}
W/System.err: java.lang.ClassCastException: com.sun.mail.imap.IMAPInputStream cannot be cast to javax.mail.Multipart

When I call message.getContent(), but I don't know if it's related to this lib in particular or changes of android 11.

In addition, before that I was unable to build my app because of the error : 
More than one file was found with OS independent path 'META-INF/NOTICE.md'.
That forced me to add in build.gradle :
    packagingOptions {
        exclude 'META-INF/LICENSE.md'
        exclude 'META-INF/NOTICE.md'
    }

(to have these errors I only updated my project to android 11 and changed the version of this lib, nothing else)
Maybe someone else can try to update to see if we have the same problems ?

**Comment by lukasj** [comment]
@AlexisDD do you have stacktrace?

wrt those md files - they are mandatory part of every binary/source jar originating from Eclipse Foundation owned repositories. Packaging options you've mentioned are part of https://eclipse-ee4j.github.io/mail/Android

**Comment by AlexisDD** [comment]
The full stacktrace :

W/javax.mail: expected resource not found: {0}
E/System.err: java.lang.ClassCastException: com.sun.mail.imap.IMAPInputStream cannot be cast to javax.mail.internet.MimeMultipart
        at fr.alexis.apptest.utils.MailUtils.getMessageContent(MailUtils.java:274)
        at fr.alexis.apptest.utils.MailUtils.lambda$sync$1(MailUtils.java:132)
        at fr.alexis.apptest.utils.-$$Lambda$MailUtils$BIMpRbrwn8ybFEZ5rlLLf35EcGc.call(Unknown Source:4)
        at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/System.err:     at java.lang.Thread.run(Thread.java:919)

I think it's not a real error in your lib, but in this version Part.getContent() is always returning a IMAPInputStream object unlike the previous version that was returning Multipart, String, ... according to the content type.
And I don't know what means the first warning but it was not displaying in 1.6.5

**Comment by lukasj** [comment]
@AlexisDD not your fault. Can you try again with updated snapshot, please? The new binary should be there in about an hour or so...

**Comment by AlexisDD** [comment]
I just tried with the updated snapshot and everything is working fine for me. Thanks for this fix !
Just a last question : I saw it is possible to update to 2.0 on android, is there an advantage to stay on 1.6.6 or it's better to switch to 2.0 ?

**Comment by lukasj** [comment]
2.0.0 is the way to go forward. Bill said 1.6.5 is the last release from 1.x. Motivation for 1.6.6 is to fix only some critical stuff 
and most visible regressions. Once 1.6.6 gets out, I do not plan to invest much time to 1.x

To make it short - use 1.x if you need java binary level 1.7; in all other cases it is recommended to move to version 2.x - officially supported minimum binary level is Java SE 8 and package names are `jakarta.mail.*` instead of `javax.mail` and `jakarta.activation` instead of `javax.activation` (simple search/replace or sed usually do the trick)

**Comment by li42899974** [comment]
> 1.6.6

hi Lukasj, i use 
implementation 'com.sun.mail:android-mail:1.6.6-SNAPSHOT'
    implementation 'com.sun.mail:android-activation:1.6.6-SNAPSHOT'
in my build.gradle
but it is not work, the error is Could not find com.sun.mail:android-activation:1.6.6-SNAPSHOT.
how should i fix it ?
thanks !

**Comment by lukasj** [comment]
@li42899974 you have to add jakarta snapshot repository configuration to you `build.gradle`

adding sth like:
```
repositories {
    maven {
        url 'https://jakarta.oss.sonatype.org/content/repositories/snapshots'
    }
}
```
there should help. NOTE: SNAPSHOTS are the least stable builds as they are being changed after every commit. They are useful mostly for testing. If you need your build to be stable and current SNAPSHOT is fine for you, then the best would be to grab the jar you need from https://jakarta.oss.sonatype.org/content/repositories/snapshots/com/sun/mail/ and use direct `file` dependency. You get build stability/reproducibility but you loose support (ie if you find an issue, you should check the latest binary before reporting it to the project)

**Comment by li42899974** [comment]
> @li42899974 you have to add jakarta snapshot repository configuration to you `build.gradle`
> 
> adding sth like:
> 
> ```
> repositories {
>     maven {
>         url 'https://jakarta.oss.sonatype.org/content/repositories/snapshots'
>     }
> }
> ```
> 
> there should help. NOTE: SNAPSHOTS are the least stable builds as they are being changed after every commit. They are useful mostly for testing. If you need your build to be stable and current SNAPSHOT is fine for you, then the best would be to grab the jar you need from https://jakarta.oss.sonatype.org/content/repositories/snapshots/com/sun/mail/ and use direct `file` dependency. You get build stability/reproducibility but you loose support (ie if you find an issue, you should check the latest binary before reporting it to the project)

thank you ! it is work !
