### ISSUE TITLE
Could not find com.sun.activation:jakarta-activation:2.0.0

### ISSUE THREAD

**Issue by li42899974** [eclipse-ee4j/mail#509]
i have add below code to build.gradle
implementation 'com.sun.mail:jakarta-mail:2.0.0'
implementation 'com.sun.activation:jakarta-activation:2.0.0'

maven { url 'https://jakarta.oss.sonatype.org/content/repositories/snapshots' }

but when i was running in android studio
the error is Could not find com.sun.activation:jakarta-activation:2.0.0
i do not know why and how to fix this ?
help me please ,thanks.

**Comment by lukasj** [comment]
Final builds are not snapshots. Use maven central instead, see: https://search.maven.org/artifact/com.sun.activation/jakarta.activation/2.0.0/jar

Note that artifact do have dot, not dash in their names now, see https://eclipse-ee4j.github.io/mail/Android
