### ISSUE TITLE
Question about 2.0.0

### ISSUE THREAD

**Issue by rcaspar** [eclipse-ee4j/mail#520]
Hello, 
I recently upgraded from 1.6.2 to 2.0.0 and it was easy to replace the imports. But I found out that there's now a dependency towards `jakarta.activation:jakarta.activation-api` in `jakarta.mail.internet.MimeMultipart`, shouldn't this be documented in the README ?
Regards,

**Comment by lukasj** [comment]
there has always been a dependency on activation. Since activation was part of JDK (till JDK 10), the dependency itself has not been immediately visible.

**Comment by rcaspar** [comment]
I see, thanks for your answer :)
