### ISSUE TITLE
1.6.6 release version maven build failed

### ISSUE THREAD

**Issue by tudvari** [eclipse-ee4j/mail#542]
**Describe the bug**
Using version 1.6.6 isn't possible, there is an incorrect version number in the parent pom. The issue is fixed with the following PR https://github.com/eclipse-ee4j/mail/pull/537

Is it possible to release version 1.6.7?

Maven build output
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.8:unpack (get-sources) on project mailapi: Unable to find artifact.: Could not find artifact com.sun.mail:jakarta.mail:jar:sources:1.6.6-SNAPSHOT
[ERROR] 
[ERROR] Try downloading the file manually from the project website.
[ERROR] 
[ERROR] Then, install it using the command: 
[ERROR]     mvn install:install-file -DgroupId=com.sun.mail -DartifactId=jakarta.mail -Dversion=1.6.6-SNAPSHOT -Dclassifier=sources -Dpackaging=jar -Dfile=/path/to/file
[ERROR] 
[ERROR] Alternatively, if you host your own repository you can deploy the file there: 
[ERROR]     mvn deploy:deploy-file -DgroupId=com.sun.mail -DartifactId=jakarta.mail -Dversion=1.6.6-SNAPSHOT -Dclassifier=sources -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]`

**Comment by lukasj** [comment]
1.6.7 is out
