### ISSUE TITLE
Fix failling build for release: 1.6.7

### ISSUE THREAD

**Issue by tudvari** [eclipse-ee4j/mail#552]
Unfortunately the build for the release v.1.6.7 is failling, can somebody fix this? CI job: https://ci.eclipse.org/mail/job/mail/job/1.6.7-BRANCH/1/ This release contains some important fix regarding the POP3 OAuth support for Office365 and Outlook.

Thanks in advance.

**Comment by lukasj** [comment]
that job will be fixed by removal. One can use [snapshots](https://eclipse-ee4j.github.io/mail/#Development_Releases) for testing
