### ISSUE TITLE
Mail 2.1 Release

### ISSUE THREAD

**Issue by Pandrex247** [eclipse-ee4j/mail#596]
Follow up on https://github.com/jakartaee/specifications/pull/428.
As per mentor review process:

Creates an issue in the specification project that includes the following checklist for the specification project team:
- [x] Promotes api staging release promotes the specification api jars to maven central. An example release job script can be found here https://wiki.eclipse.org/MavenReleaseScript.
- [x] Go through the merged jakarta.ee specification website page to verify all the links are valid.
- [x] If XML Schemas are published on https://jakarta.ee/schemas, send a PR to update the status from Draft to Final.
- [x] Approve the compatibility request.
- [x] The compatible implementation project/vendor MUST send an email to [tck@eclipse.org](mailto:tck@eclipse.org) for approval of the compatible implementation for trademark usage.
- [x] Merge any final release branch as appropriate for the branch management for the project.

**Comment by lukasj** [comment]
done
