### ISSUE TITLE
expected resource not found: /META-INF/javamail.default.address.map

### ISSUE THREAD

**Issue by leonardwoo** [eclipse-ee4j/mail#598]
**Describe the bug**
When I use Jakarta Mail 2.1.0 as a mail client, the following warning is printed:
 jakarta.mail.Session loadResource
WARNING: expected resource not found: /META-INF/javamail.default.address.map

Provider is [Angus Mail](https://github.com/eclipse-ee4j/angus-mail)

For specific questions, please see https://github.com/eclipse-ee4j/angus-mail/issues/18

Thank you

**Comment by jbescos** [comment]
PR https://github.com/eclipse-ee4j/mail/pull/599
