### ISSUE TITLE
Provider for "jakarta.activation.spi.MailcapRegistryProvider" cannot be found

### ISSUE THREAD

**Issue by sundarsabapathi** [eclipse-ee4j/mail#624]
I used the below dependency in my project
```
<dependency>
  <groupId>com.sun.mail</groupId>
  <artifactId>jakarta.mail</artifactId>
  <version>2.0.1</version>
</dependency>

```
I am trying to send an email the following exception is  "java.lang.RuntimeException: Provider for jakarta.activation.spi.MailcapRegistryProvider cannot be found" thrown continuously if I use the v1.6.7 it works as expected email also send successfully.  I do not know why and how to fix this ? Please help me to give some idea to resolve the exception, Thanks

**Comment by jbescos** [comment]
It is missing jakarta activation implementation.

You can fix it replacing that dependency by:

```
<dependency>
    <groupId>org.eclipse.angus</groupId>
    <artifactId>angus-mail</artifactId>
    <version>1.0.0</version>
</dependency>
```

That brings mail-api, the implementation (angus-mail), activation-api and the implementation (angus-activation).

**Comment by psyked222** [comment]
Thanks, it worked for me ! 
I had no idea why Jakarta-mail couldn't find its providers.

Note : I had to downgrade jakarta.activation-api from 2.1.0 to 2.0.1 (using jakarta.mail 2.0.1) due to this error : 
```
Can't send email: java.lang.ArrayStoreException: arraycopy: element type mismatch: can not cast one of the elements of java.lang.Object[] to the type of the destination array, jakarta.activation.MailcapRegistry
	at java.base/java.lang.System.arraycopy(Native Method)
	at java.base/java.util.ArrayList.toArray(ArrayList.java:401)
	at jakarta.activation.MailcapCommandMap.<init>(MailcapCommandMap.java:181)
	at jakarta.activation.CommandMap.getDefaultCommandMap(CommandMap.java:60)
	at jakarta.activation.DataHandler.getCommandMap(DataHandler.java:128)
	at jakarta.activation.DataHandler.getDataContentHandler(DataHandler.java:587)
	at jakarta.activation.DataHandler.getContent(DataHandler.java:515)
	at jakarta.mail.internet.MimeBodyPart.updateHeaders(MimeBodyPart.java:1505)
	at jakarta.mail.internet.MimeMessage.updateHeaders(MimeMessage.java:2246)
	at jakarta.mail.internet.MimeMessage.saveChanges(MimeMessage.java:2206)
	at jakarta.mail.Transport.send(Transport.java:99)

**Comment by jbescos** [comment]
Is that the whole stacktrace of the exception or is there any cause?.

Could you run also `mvn dependency:tree` in your project?.

**Comment by sundarsabapathi** [comment]
Thanks @jbescos I follow below your suggestion to resolve my issue.

> It is missing jakarta activation implementation.
> 
> You can fix it replacing that dependency by:
> 
> ```
> <dependency>
>     <groupId>org.eclipse.angus</groupId>
>     <artifactId>angus-mail</artifactId>
>     <version>1.0.0</version>
> </dependency>
> ```
> 
> That brings mail-api, the implementation (angus-mail), activation-api and the implementation (angus-activation).

**Comment by psyked222** [comment]
>  the stacktrace started from my code calling `SMTPTransport.send(message)` but i could go back on version 2.1.0 after excluding com.sun.mail.jakarta.mail from another dependency (subethasmtp).
